name: CI

on:
  push:
    branches: [main]

env:
  REGISTRY: "registry.digitalocean.com/codepumper"
  IMAGE_NAME: "medusa"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build and push backend image
        run: |
          docker build -t ${REGISTRY}/${IMAGE_NAME}-backend:${GITHUB_SHA} -f ./backend/Dockerfile ./backend
          docker push ${REGISTRY}/${IMAGE_NAME}-backend:${GITHUB_SHA}

      - name: Build and push admin image
        run: |
          docker build -t ${REGISTRY}/${IMAGE_NAME}-admin:${GITHUB_SHA} -f ./admin/Dockerfile ./admin
          docker push ${REGISTRY}/${IMAGE_NAME}-admin:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA
          script: |
            # Pull the latest images
            docker pull ${REGISTRY}/${IMAGE_NAME}-backend:${GITHUB_SHA}
            docker pull ${REGISTRY}/${IMAGE_NAME}-admin:${GITHUB_SHA}

            # Stop and remove old containers
            docker-compose down

            # Start new containers with the latest images
            docker-compose up -d
